- Refactor: Move Spring controllers from fenixedu-candidacies-extensi…
qub-it/fenixedu-ulisboa-specifications pull request #25
Opened 2024-05-03 17:01 UTC by anilmamede

I moved the Spring controllers from fenixedu-candidacies-extensions to this module

2024-05-06 11:02 UTC, pabrantes requested changes
@anilmamede let's remove the OMNIS.CLOUD SOFTWARE license from the source code, that was in the previous module where the code was.

2024-05-09 08:44 UTC, anilmamede commented
@pabrantes @joaofreitas-qubit I removed the license from the added files

2024-05-09 08:45 UTC, joaofreitas-qubit approved these changes

2024-05-09 08:46 UTC, pabrantes approved these changes

2024-05-09 09:23 UTC, merged